#어떤 이미지로부터 새로운 이미지를 생성할지를 지정
FROM node:12

# Dockerfile을 생성/관리하는 사람
MAINTAINER YongJun Kang <yj.kang@zipida.com>

# /app 디렉토리 생성
RUN mkdir -p /app

# /app 디렉토리를 WORKDIR로 설정
WORKDIR /app

# 현재 Dockerfile이 잇는 경로의 모든 파일을 /app 에 복사하기 위해 추가
ADD . /app

# npm install 을 실행해서 모듈을 받는다
RUN npm install

# 환경변수 NODE_ENV의 값을 development 로 설정
ENV NODE_ENV development

# 가상 머신에서 오픈할 포트
EXPOSE 3000

# 컨테이너에서 실행될 명령을 지정
CMD ["npm", "start"]