#docker-compose의 버전을 명시. 버전별로 명령어등의 약간의 차이가 있다.
version: "2"

services:
  redis:
    image: redis:latest
    expose:
      - "6379"
    ports:
      - "6379:6379"
  node-app:
    build: .
    #image: yjkang95/simple-web-chat:redis
    ports:
      - "4884:4884"
    links: 
      - redis